name = "synpixel/base64"
version = "3.0.0"
description = "A copy of Reselim's Base64, for pesde"
authors = ["Reselim"]
repository = "https://github.com/synpixel/Base64"
license = "MIT"
includes = []

[indices]
default = "https://github.com/daimond113/pesde-index"
